// utils/data.js
export const projects = [
  {
    id: 1,
    title: "Skin Cancer Classification (Research)",
    description:
      "Designed hybrid architecture combining frozen ResNet50 feature extractor with four-head Vision Transformer blocks, attaining 96.3% accuracy and macro F1 of 0.961 on HAM10000 dataset. Integrated Global Average Pooling and multi-head self-attention for seven-class skin lesion classification, achieving Area Under Curve of 1.00 across all classes. Accepted and presented at IEEE World Conference on Applied Intelligence and Computing (AIC 2025) to 100+ attendees.",
    technologies: [
      "Python",
      "TensorFlow",
      "PyTorch",
      "Deep Learning",
      "Computer Vision",
      "Medical AI",
      "ResNet50",
      "Vision Transformer",
      "HAM10000 Dataset",
      "Image Classification",
    ],
    category: "Research",
    github: null,
    live: null,
    image: "/skin-cancer.jpg",
    impact: "Medical AI Research - Accepted at IEEE AIC 2025",
    status: "Accepted",
  },
  {
    id: 2,
    title: "Brain Tumor Segmentation (Research)",
    description:
      "Led innovation by designing VGG16-based encoder with Multi-Channel Attention decoder achieving 99.59% accuracy and 99.71% specificity on LGG Brain MRI Segmentation dataset from 110 low-grade glioma patients. Implemented ensemble learning combining multiple model configurations, improving Dice coefficient by 3.7% over standard UNet. Applied data engineering with preprocessing pipeline implementing skull stripping, intensity normalization, and resizing to 256x256 pixels for FLAIR MRI scans.",
    technologies: [
      "Python",
      "TensorFlow",
      "PyTorch",
      "Deep Learning",
      "Computer Vision",
      "Medical Imaging",
      "UNet",
      "VGG16",
      "Multi-Channel Attention",
      "FLAIR MRI Processing",
    ],
    category: "Research",
    github: null,
    live: null,
    image: "/brain-tumor.jpg",
    impact: "Medical AI Research - Under Review at Elsevier",
    status: "Under Review",
  },
  {
    id: 3,
    title:
      "Extended ResNet50 with Inverse Soft Mask Attention for Skin Cancer (Research)",
    description:
      "Developed two-stage pipeline combining U-Net++ hair segmentation with Extended ResNet50 classifier featuring Inverse Soft Mask Attention mechanism, achieving 97.89% accuracy on HAM10000 dataset with 10,015 dermoscopic images. Applied creativity by integrating dense residual blocks and Squeeze-and-Excitation modules with learnable weighted feature aggregation for hair-occluded and unoccluded regions. Utilized Nadam optimizer with Cosine Decay Restarts and Sparse Categorical Crossentropy loss, incorporating explainable AI principles ensuring model deployment readiness.",
    technologies: [
      "Python",
      "TensorFlow",
      "PyTorch",
      "Deep Learning",
      "Computer Vision",
      "Medical AI",
      "ResNet50",
      "Inverse Soft Mask Attention",
      "U-Net++",
      "HAM10000 Dataset",
      "Image Classification",
    ],
    category: "Research",
    github: null,
    live: null,
    image: "/skin-cancer-advanced.jpg",
    impact: "Medical AI Research - Submitted to Journal",
    status: "Submitted",
  },
  {
    id: 4,
    title: "TrackMania Reinforcement Learning Agent",
    description:
      "Developed an advanced reinforcement learning agent for TrackMania racing game using Implicit Quantile Networks (IQN). The agent learns optimal racing strategies through trial and error, achieving competitive lap times and demonstrating robust decision-making in unpredictable racing situations.",
    technologies: [
      "Python",
      "PyTorch",
      "Reinforcement Learning",
      "Implicit Quantile Networks",
      "Neural Networks",
      "Computer Vision",
      "dxcam",
    ],
    category: "AI/ML Core",
    github: "https://github.com/ShubhamGajjar/TrackMania-ReinforcementLearning",
    live: null,
    image: "/trackmania.jpg",
    impact: "Game AI & RL Research",
    status: "Completed",
  },
  {
    id: 5,
    title: "Twitter Sentiment Analysis (NLP Project)",
    description:
      "Built a comprehensive sentiment analysis system using Twitter API to analyze public sentiment on various topics. Implements NLP techniques and machine learning models for real-time sentiment classification.",
    technologies: [
      "Python",
      "Twitter API",
      "NLP",
      "Machine Learning",
      "Pandas",
      "NLTK",
      "TextBlob",
      "Google Colab",
    ],
    category: "Data Science",
    github: "https://github.com/ShubhamGajjar/Twitter-Sentiment-Analysis.git",
    live: null,
    image: "/sentiment.jpg",
    impact: "Social Media Analytics",
    status: "Completed",
  },
];

export const skills = {
  "AI/ML Core": [
    "Deep Learning",
    "Machine Learning",
    "Neural Networks",
    "Computer Vision",
    "Natural Language Processing",
    "Reinforcement Learning",
    "Evolutionary Algorithms",
  ],
  "Deep Learning Frameworks": [
    "TensorFlow",
    "PyTorch",
    "Keras",
    "Transformers",
    "CNN/ResNet",
    "RNN/LSTM",
    "Vision Transformers",
    "UNet Architectures",
    "FastAPI",
    "Hugging Face",
  ],
  "Computer Vision": [
    "OpenCV",
    "Medical Imaging",
    "Image Segmentation",
    "Object Detection",
    "Image Classification",
    "FLAIR MRI Processing",
    "Dermatoscopic Analysis",
  ],
  "Data Science & Analytics": [
    "Python",
    "Pandas",
    "NumPy",
    "Scikit-learn",
    "Matplotlib",
    "Seaborn",
    "Statistical Analysis",
  ],
  "Research & Development": [
    "Academic Writing",
    "Literature Review",
    "Experimental Design",
    "IEEE Publications",
    "Research Methodology",
    "Medical AI Research",
  ],
  "Game AI & RL": [
    "Reinforcement Learning",
    "Deep Q-Networks",
    "Genetic Algorithms",
    "Game AI Development",
    "Neural Network Training",
  ],
  "Cloud & DevOps": ["Docker", "GitHub Actions"],
  Tools: ["Jupyter", "VSCode", "Google Colab"],
  "Leadership & Adaptability": [
    "Team Leadership",
    "Adaptability",
    "Problem Solving",
    "Communication",
    "Collaboration",
  ],
};

export const researchPapers = [
  {
    id: 1,
    title: "Hybrid ResNet-ViT for Skin Cancer Classification",
    authors:
      "Shubham Gajjar, Harshal Joshi, Om Rathod, Vishal Barot, Deep Joshi",
    conference:
      "4th IEEE World Conference on Applied Intelligence and Computing (AIC 2025)",
    status: "Accepted",
    year: "2025",
    description:
      "Designed hybrid architecture combining frozen ResNet50 feature extractor with four-head Vision Transformer blocks, attaining 96.3% accuracy and macro F1 of 0.961 on HAM10000 dataset. Integrated Global Average Pooling and multi-head self-attention for seven-class skin lesion classification, achieving Area Under Curve of 1.00 across all classes. Accepted and presented at IEEE World Conference on Applied Intelligence and Computing (AIC 2025) to 100+ attendees.",
    keywords: [
      "Computer Vision",
      "Deep Learning",
      "Medical AI",
      "Skin Cancer",
      "ResNet",
      "Vision Transformer",
    ],
    doi: "10.1109/AIC60235.2025.11212073",
    ieeeUrl: "https://ieeexplore.ieee.org/document/11212073",
    pdf: "/AIC 2025 Certificate.pdf",
    certificate: "/AIC_2025_Presentation_Certificate.pdf",
    abstract:
      "Correct identification of different skin lesions, such as melanoma, from dermatoscopic images is a major challenge for automated systems, thus causing delay in early diagnosis. Most of the current models are unable to achieve an optimal balance between local feature extraction and global context understanding. Our work overcomes this challenge by proposing a hybrid ResNet50-ViT model. This architecture combines frozen ResNet50 feature extractor with four-head Vision Transformer blocks, allowing the categorization of seven lesion classes from the HAM10000 dataset by fusing ViT's global context awareness with ResNet's strong local feature extraction. The designed model demonstrated 96.3% accuracy, macro F1 of 0.961, and Area Under Curve of 1.00 across all classes, which is a major breakthrough in computer-aided dermatological diagnosis.",
  },
  {
    id: 2,
    title: "VGG16-MCA UNet for Brain Tumor Segmentation",
    authors: "Shubham Gajjar, Deep Joshi, Avi Poptani, Vishal Barot",
    conference: "Elsevier",
    status: "Under Review",
    year: "2025",
    description:
      "Led innovation by designing VGG16-based encoder with Multi-Channel Attention decoder achieving 99.59% accuracy and 99.71% specificity on LGG Brain MRI Segmentation dataset from 110 low-grade glioma patients. Implemented ensemble learning combining multiple model configurations, improving Dice coefficient by 3.7% over standard UNet. Applied data engineering with preprocessing pipeline implementing skull stripping, intensity normalization, and resizing to 256x256 pixels for FLAIR MRI scans.",
    keywords: [
      "Computer Vision",
      "Deep Learning",
      "Medical AI",
      "Brain Tumor",
      "UNet",
      "FLAIR MRI",
      "Multi-Channel Attention",
    ],
    doi: "Pending",
    abstract:
      "Computer vision-based automated brain tumor segmentation is crucial in medical imaging for accurate diagnosis and treatment planning. This research proposes a novel hybrid deep learning approach combining VGG16 architecture with Multi-Channel Attention (MCA) and UNet for enhanced brain tumor segmentation in FLAIR MRI images. The proposed VGG16-MCA UNet architecture leverages VGG16's robust feature extraction capabilities, enhanced by multi-channel attention mechanisms that capture both local and global spatial information. The model achieved 99.59% accuracy and 99.71% specificity on LGG Brain MRI Segmentation dataset from 110 low-grade glioma patients. Ensemble learning combining multiple model configurations improved Dice coefficient by 3.7% over standard UNet. The preprocessing pipeline implements skull stripping, intensity normalization, and resizing to 256x256 pixels for FLAIR MRI scans, adhering to AI ethics for medical applications. This work contributes to the advancement of automated medical image analysis with potential applications in clinical decision support systems.",
  },
  {
    id: 3,
    title: "Extended ResNet50 with Inverse Soft Mask Attention for Skin Cancer",
    authors:
      "Shubham Gajjar, Harshal Joshi, Om Rathod, Vishal Barot, Deep Joshi",
    conference: "Journal Submission",
    status: "Submitted",
    year: "2025",
    description:
      "Developed two-stage pipeline combining U-Net++ hair segmentation with Extended ResNet50 classifier featuring Inverse Soft Mask Attention mechanism, achieving 97.89% accuracy on HAM10000 dataset with 10,015 dermoscopic images. Applied creativity by integrating dense residual blocks and Squeeze-and-Excitation modules with learnable weighted feature aggregation for hair-occluded and unoccluded regions. Utilized Nadam optimizer with Cosine Decay Restarts and Sparse Categorical Crossentropy loss, incorporating explainable AI principles ensuring model deployment readiness.",
    keywords: [
      "Computer Vision",
      "Deep Learning",
      "Medical AI",
      "Skin Cancer",
      "ResNet",
      "Inverse Soft Mask Attention",
      "U-Net++",
    ],
    doi: "Pending",
    abstract:
      "Skin cancer detection from dermoscopic images is challenging due to hair occlusion and varying lesion characteristics. This work presents an extended ResNet50 architecture with Inverse Soft Mask Attention mechanism for robust skin cancer classification. The two-stage pipeline first uses U-Net++ for precise hair segmentation, then employs Extended ResNet50 classifier with Inverse Soft Mask Attention to process both hair-occluded and unoccluded regions. The architecture integrates dense residual blocks and Squeeze-and-Excitation modules with learnable weighted feature aggregation, enabling the model to handle complex dermatoscopic images. Training utilizes Nadam optimizer with Cosine Decay Restarts and Sparse Categorical Crossentropy loss. The model achieved 97.89% accuracy on HAM10000 dataset with 10,015 dermoscopic images, demonstrating superior performance in handling hair-occluded lesions. This work incorporates explainable AI principles, ensuring model deployment readiness for clinical applications.",
  },
];

export const socialLinks = {
  email: "gajjar.shu@northeastern.edu",
  github: "https://github.com/ShubhamGajjar",
  linkedin: "https://www.linkedin.com/in/implici7/",
  googleScholar: "https://scholar.google.com/citations?user=MDS9t3QAAAAJ&hl=en",
  orcid: "https://orcid.org/0009-0007-4654-2525",
};

export const experience = "7+ months";
